### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gitatmax**
Sorry for the hold up. I hope this is better!

### CODE REVIEW

**Comment by deanishe** [comment]
Thanks for fixing the image links, but the other changes kinda mess things up.

The TOC is auto-generated by a Sublime plugin, and you've removed its config and all its anchors :(

**Comment by gitatmax** [comment]
Whoops! Take 3!

**Comment by deanishe** [comment]
Sorry, could you limit the PR to fixes for the icon URLs and any other actual errors?

Most of changes are stylistic, and I'm quite happy with my style. Reference-style links, British spelling and sentence case for titles are deliberate choices.

**Comment by gitatmax** [comment]
Don't be sorry! Sure thing.

**Pull request closed without merging**
